Switch to real image usage

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -85,3 +85,28 @@ jobs:
         file: ./coverage.xml
         flags: unit
         fail_ci_if_error: false
+
+  publish:
+    runs-on: ubuntu-latest
+    needs: test
+    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
+    steps:
+    - name: Login to GitHub Container Registry
+      uses: docker/login-action@v1
+      with:
+        registry: ghcr.io
+        username: ${{ github.actor }}
+        password: ${{ secrets.GITHUB_TOKEN }}
+    - name: Set tag
+      run: |
+        VERSION="${GITHUB_REF#refs/tags/v}"
+        TEST="image: ghcr.io/aio-libs/get-releasenotes:${VERSION}"
+        if [[ grep -F "$TEST" action.yml ]]; then
+          echo "::error::Image tag in action.yml mismatches with github tag"
+          exit 1
+        fi
+        echo "TAG=ghcr.io/aio-libs/get-releasenotes:${VERSION}" >> $GITHUB_ENV
+    - name: Build Docker Image
+      run: docker build -t "${TAG}" .
+    - name: Push Docker Image
+      run: docker push "${TAG}" .
